### ISSUE TITLE
Build fails due to missing Templates

### ISSUE THREAD

**Issue by trieloff** [adobe/parcel-plugin-htl#1]
```
⏳  Building html.htl...
🚨  /code/project-helix/prototypes/parcel-plugin-pipeline/test/integration/htl-only/src/html.htl: ENOENT: no such file or directory, open '/code/project-helix/prototypes/parcel-plugin-pipeline/test/integration/htl-only/node_modules/@adobe/parcel-plugin-htl/node_modules/@adobe/htlengine/src/compiler/JSRuntimeTemplate.js'
    at Object.fs.openSync (fs.js:646:18)
    at Object.fs.readFileSync (fs.js:551:33)
    at TransientCompiler.compile (/code/project-helix/prototypes/parcel-plugin-pipeline/test/integration/htl-only/node_modules/@adobe/parcel-plugin-htl/HTLAsset.js:41:23)
    at HTLAsset.parse (/code/project-helix/prototypes/parcel-plugin-pipeline/test/integration/htl-only/node_modules/@adobe/parcel-plugin-htl/HTLAsset.js:64:30)
    at HTLAsset.parseIfNeeded (/code/project-helix/prototypes/parcel-plugin-pipeline/test/integration/htl-only/node_modules/parcel-bundler/src/Asset.js:62:29)
    at <anonymous>
```

Depends on adobe/htlengine#3

**Comment by tripodsan** [comment]
why is this missing: `parcel-plugin-htl/node_modules/@adobe/htlengine/src/compiler/JSRuntimeTemplate.js` ?

**Comment by trieloff** [comment]
This file is available when I run it in my integration tests, where I use `file:` dependencies that create a symlink (so the file itself is there). The better solution is to keep the compile to string method in htlengine, and then just use it as #2 does.

**Comment by tripodsan** [comment]
but this file is needed is read from the filesystem and is the _template_ for the generated code. this cannot be inlined.
